version: "3.2"

services:
  shell:
    image: node:12.18.2
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: ["/bin/sh"]

  dev:
    image: node:12.18.2
    working_dir: /usr/src/app
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    depends_on:
      - mongo
    command: ["/bin/sh", "-c", "node app.js"]
  
  mongo:
    image: mongo:4.2.8
    volumes:
      - /data/db