const FETCH_MOVIES_BEGIN = 'FETCH_MOVIES_BEGIN';
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

const FETCH_MOVIE_DETAILS_BEGIN = 'FETCH_MOVIE_DETAILS_BEGIN'
const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS'

export {
    FETCH_MOVIES_BEGIN,
    FETCH_MOVIES_SUCCESS,
    FETCH_MOVIES_FAILURE,

    FETCH_MOVIE_DETAILS_BEGIN,
    FETCH_MOVIE_DETAILS_SUCCESS
}