const SEARCH_MOVIES_BEGIN = 'SEARCH_MOVIES_BEGIN';
const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

export {
    SEARCH_MOVIES_BEGIN,
    SEARCH_MOVIES_SUCCESS,
    SEARCH_MOVIES_FAILURE
}